package com.at.springboot.mybatis.po;

/**
 *
 * <pre>
 * <code>
 * USE test
 * ;
 * drop table if exists json_user
 * ;
 * create table json_user (
 *     id int not null auto_increment
 *     , user_name varchar(20)
 *     , last_login_info json
 *     , primary key (id)
 * ) ENGINE=InnoDB  DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_520_ci
 * ;
 * 
 * -- data
 * insert into json_user(user_name, last_login_info)
 * values
 * ("kay",'{"time":"2015-01-01 13:00:00","ip":"192.168.1.1","result":"fail"}')
 * ,("bob",'{"time":"2015-01-07 06:44:00","ip":"192.168.1.4","result":"success"}')
 * ,("lucy", JSON_OBJECT("time", now(),"ip", "192.168.1.4","result", "success"))
 * ;
 * commit
 * ;
 * </code>
 * </pre>
 *
 */
public class JsonUser {

    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column json_user.id
     * @mbg.generated  Sat Jan 19 21:31:04 CST 2019
     */
    private Integer id;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column json_user.user_name
     * @mbg.generated  Sat Jan 19 21:31:04 CST 2019
     */
    private String userName;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column json_user.last_login_info
     * @mbg.generated  Sat Jan 19 21:31:04 CST 2019
     */
    private String lastLoginInfo;

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column json_user.id
     * @return  the value of json_user.id
     * @mbg.generated  Sat Jan 19 21:31:04 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column json_user.id
     * @param id  the value for json_user.id
     * @mbg.generated  Sat Jan 19 21:31:04 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column json_user.user_name
     * @return  the value of json_user.user_name
     * @mbg.generated  Sat Jan 19 21:31:04 CST 2019
     */
    public String getUserName() {
        return userName;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column json_user.user_name
     * @param userName  the value for json_user.user_name
     * @mbg.generated  Sat Jan 19 21:31:04 CST 2019
     */
    public void setUserName(String userName) {
        this.userName = userName == null ? null : userName.trim();
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column json_user.last_login_info
     * @return  the value of json_user.last_login_info
     * @mbg.generated  Sat Jan 19 21:31:04 CST 2019
     */
    public String getLastLoginInfo() {
        return lastLoginInfo;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column json_user.last_login_info
     * @param lastLoginInfo  the value for json_user.last_login_info
     * @mbg.generated  Sat Jan 19 21:31:04 CST 2019
     */
    public void setLastLoginInfo(String lastLoginInfo) {
        this.lastLoginInfo = lastLoginInfo == null ? null : lastLoginInfo.trim();
    }
}
