package com.at.springboot.mybatis.po;

/**
 *
 * <pre>
 * <code>
 * USE test
 * ;
 * 
 * -- create table
 * drop table if exists json_user
 * ;
 * create table json_user (
 *     id int not null auto_increment
 *     , user_name varchar(20)
 *     , last_login_info json
 *     , primary key (id)
 * ) ENGINE=InnoDB  DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_520_ci
 * ;
 * ALTER TABLE json_user
 *     ADD last_login_result VARCHAR(15) GENERATED ALWAYS AS (JSON_UNQUOTE(JSON_EXTRACT(last_login_info, '$.result')))
 *     VIRTUAL
 * ;
 * ALTER TABLE json_user
 *     ADD index idx_json_user_result(last_login_result)
 * ;
 * 
 * 
 * -- data
 * insert into json_user(user_name, last_login_info)
 * values
 * ("kay",'{"time":"2015-01-01 13:00:00","ip":"192.168.1.1","result":"fail"}')
 * ,("bob",'{"time":"2015-01-07 06:44:00","ip":"192.168.1.4","result":"success"}')
 * ,("lucy", JSON_OBJECT("time", now(),"ip", "192.168.1.4","result", "success"))
 * ;
 * commit
 * ;
 * </code>
 * </pre>
 *
 */
public class JsonUser {

    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column json_user.id
     * @mbg.generated  Sun Jan 20 12:49:45 CST 2019
     */
    private Integer id;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column json_user.user_name
     * @mbg.generated  Sun Jan 20 12:49:45 CST 2019
     */
    private String userName;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column json_user.last_login_result
     * @mbg.generated  Sun Jan 20 12:49:45 CST 2019
     */
    private String lastLoginResult;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column json_user.last_login_info
     * @mbg.generated  Sun Jan 20 12:49:45 CST 2019
     */
    private String lastLoginInfo;

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column json_user.id
     * @return  the value of json_user.id
     * @mbg.generated  Sun Jan 20 12:49:45 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column json_user.id
     * @param id  the value for json_user.id
     * @mbg.generated  Sun Jan 20 12:49:45 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column json_user.user_name
     * @return  the value of json_user.user_name
     * @mbg.generated  Sun Jan 20 12:49:45 CST 2019
     */
    public String getUserName() {
        return userName;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column json_user.user_name
     * @param userName  the value for json_user.user_name
     * @mbg.generated  Sun Jan 20 12:49:45 CST 2019
     */
    public void setUserName(String userName) {
        this.userName = userName == null ? null : userName.trim();
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column json_user.last_login_result
     * @return  the value of json_user.last_login_result
     * @mbg.generated  Sun Jan 20 12:49:45 CST 2019
     */
    public String getLastLoginResult() {
        return lastLoginResult;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column json_user.last_login_result
     * @param lastLoginResult  the value for json_user.last_login_result
     * @mbg.generated  Sun Jan 20 12:49:45 CST 2019
     */
    public void setLastLoginResult(String lastLoginResult) {
        this.lastLoginResult = lastLoginResult == null ? null : lastLoginResult.trim();
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column json_user.last_login_info
     * @return  the value of json_user.last_login_info
     * @mbg.generated  Sun Jan 20 12:49:45 CST 2019
     */
    public String getLastLoginInfo() {
        return lastLoginInfo;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column json_user.last_login_info
     * @param lastLoginInfo  the value for json_user.last_login_info
     * @mbg.generated  Sun Jan 20 12:49:45 CST 2019
     */
    public void setLastLoginInfo(String lastLoginInfo) {
        this.lastLoginInfo = lastLoginInfo == null ? null : lastLoginInfo.trim();
    }
}
