package com.at.springboot.mybatis.mapper;

import com.at.springboot.mybatis.po.JsonUser;
import com.at.springboot.mybatis.po.JsonUserExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface JsonUserMapper {

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table json_user
     * @mbg.generated  Sat Jan 19 21:31:04 CST 2019
     */
    long countByExample(JsonUserExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table json_user
     * @mbg.generated  Sat Jan 19 21:31:04 CST 2019
     */
    int deleteByExample(JsonUserExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table json_user
     * @mbg.generated  Sat Jan 19 21:31:04 CST 2019
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table json_user
     * @mbg.generated  Sat Jan 19 21:31:04 CST 2019
     */
    int insert(JsonUser record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table json_user
     * @mbg.generated  Sat Jan 19 21:31:04 CST 2019
     */
    int insertSelective(JsonUser record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table json_user
     * @mbg.generated  Sat Jan 19 21:31:04 CST 2019
     */
    List<JsonUser> selectByExampleWithBLOBs(JsonUserExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table json_user
     * @mbg.generated  Sat Jan 19 21:31:04 CST 2019
     */
    List<JsonUser> selectByExample(JsonUserExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table json_user
     * @mbg.generated  Sat Jan 19 21:31:04 CST 2019
     */
    JsonUser selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table json_user
     * @mbg.generated  Sat Jan 19 21:31:04 CST 2019
     */
    int updateByExampleSelective(@Param("record") JsonUser record, @Param("example") JsonUserExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table json_user
     * @mbg.generated  Sat Jan 19 21:31:04 CST 2019
     */
    int updateByExampleWithBLOBs(@Param("record") JsonUser record, @Param("example") JsonUserExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table json_user
     * @mbg.generated  Sat Jan 19 21:31:04 CST 2019
     */
    int updateByExample(@Param("record") JsonUser record, @Param("example") JsonUserExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table json_user
     * @mbg.generated  Sat Jan 19 21:31:04 CST 2019
     */
    int updateByPrimaryKeySelective(JsonUser record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table json_user
     * @mbg.generated  Sat Jan 19 21:31:04 CST 2019
     */
    int updateByPrimaryKeyWithBLOBs(JsonUser record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table json_user
     * @mbg.generated  Sat Jan 19 21:31:04 CST 2019
     */
    int updateByPrimaryKey(JsonUser record);
}