package com.at.spring.mybatis.po;

import java.util.Date;

/**
 * <pre>
 * <code>
 * USE test;
 * DROP TABLE IF EXISTS `blog`;
 * CREATE TABLE `blog` (
 *   `blog_id` bigint unsigned NOT NULL AUTO_INCREMENT,
 *   `name` varchar(64) DEFAULT NULL,
 *   `content` varchar(512) DEFAULT NULL,
 *   `created_datetime` datetime DEFAULT null,
 *   `updated_datetime` datetime DEFAULT null,
 *   PRIMARY KEY (`blog_id`)
 * ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
 * 
 * insert into `blog` (`name`, `content`, `created_datetime`, `updated_datetime`) values
 *  ('name1', 'content1', now(), now())
 * ,('name2', 'content2', now(), now())
 * ,('name3', 'content3', now(), now())
 * ,('name4', 'content4', now(), now())
 * ,('name5', 'content5', now(), now())
 * ;
 * commit
 * ;
 * </code>
 * </pre>
 *
 */

public class Blog {

    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column blog.blog_id
     * @mbg.generated  Sat Jan 19 18:53:52 CST 2019
     */
    private Long blogId;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column blog.name
     * @mbg.generated  Sat Jan 19 18:53:52 CST 2019
     */
    private String name;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column blog.content
     * @mbg.generated  Sat Jan 19 18:53:52 CST 2019
     */
    private String content;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column blog.created_datetime
     * @mbg.generated  Sat Jan 19 18:53:52 CST 2019
     */
    private Date createdDatetime;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column blog.updated_datetime
     * @mbg.generated  Sat Jan 19 18:53:52 CST 2019
     */
    private Date updatedDatetime;

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column blog.blog_id
     * @return  the value of blog.blog_id
     * @mbg.generated  Sat Jan 19 18:53:52 CST 2019
     */
    public Long getBlogId() {
        return blogId;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column blog.blog_id
     * @param blogId  the value for blog.blog_id
     * @mbg.generated  Sat Jan 19 18:53:52 CST 2019
     */
    public void setBlogId(Long blogId) {
        this.blogId = blogId;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column blog.name
     * @return  the value of blog.name
     * @mbg.generated  Sat Jan 19 18:53:52 CST 2019
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column blog.name
     * @param name  the value for blog.name
     * @mbg.generated  Sat Jan 19 18:53:52 CST 2019
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column blog.content
     * @return  the value of blog.content
     * @mbg.generated  Sat Jan 19 18:53:52 CST 2019
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column blog.content
     * @param content  the value for blog.content
     * @mbg.generated  Sat Jan 19 18:53:52 CST 2019
     */
    public void setContent(String content) {
        this.content = content == null ? null : content.trim();
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column blog.created_datetime
     * @return  the value of blog.created_datetime
     * @mbg.generated  Sat Jan 19 18:53:52 CST 2019
     */
    public Date getCreatedDatetime() {
        return createdDatetime;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column blog.created_datetime
     * @param createdDatetime  the value for blog.created_datetime
     * @mbg.generated  Sat Jan 19 18:53:52 CST 2019
     */
    public void setCreatedDatetime(Date createdDatetime) {
        this.createdDatetime = createdDatetime;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column blog.updated_datetime
     * @return  the value of blog.updated_datetime
     * @mbg.generated  Sat Jan 19 18:53:52 CST 2019
     */
    public Date getUpdatedDatetime() {
        return updatedDatetime;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column blog.updated_datetime
     * @param updatedDatetime  the value for blog.updated_datetime
     * @mbg.generated  Sat Jan 19 18:53:52 CST 2019
     */
    public void setUpdatedDatetime(Date updatedDatetime) {
        this.updatedDatetime = updatedDatetime;
    }
}