package com.at.springboot.mybatis.po;

import java.time.LocalDateTime;

public class UuidUser {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column uuid_user.bid
     *
     * @mbg.generated Thu Apr 25 18:56:40 CST 2019
     */
    private byte[] bid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column uuid_user.cid
     *
     * @mbg.generated Thu Apr 25 18:56:40 CST 2019
     */
    private String cid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column uuid_user.name
     *
     * @mbg.generated Thu Apr 25 18:56:40 CST 2019
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column uuid_user.created_datetime
     *
     * @mbg.generated Thu Apr 25 18:56:40 CST 2019
     */
    private LocalDateTime createdDatetime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column uuid_user.updated_datetime
     *
     * @mbg.generated Thu Apr 25 18:56:40 CST 2019
     */
    private LocalDateTime updatedDatetime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column uuid_user.bid
     *
     * @return the value of uuid_user.bid
     *
     * @mbg.generated Thu Apr 25 18:56:40 CST 2019
     */
    public byte[] getBid() {
        return bid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column uuid_user.bid
     *
     * @param bid the value for uuid_user.bid
     *
     * @mbg.generated Thu Apr 25 18:56:40 CST 2019
     */
    public void setBid(byte[] bid) {
        this.bid = bid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column uuid_user.cid
     *
     * @return the value of uuid_user.cid
     *
     * @mbg.generated Thu Apr 25 18:56:40 CST 2019
     */
    public String getCid() {
        return cid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column uuid_user.cid
     *
     * @param cid the value for uuid_user.cid
     *
     * @mbg.generated Thu Apr 25 18:56:40 CST 2019
     */
    public void setCid(String cid) {
        this.cid = cid == null ? null : cid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column uuid_user.name
     *
     * @return the value of uuid_user.name
     *
     * @mbg.generated Thu Apr 25 18:56:40 CST 2019
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column uuid_user.name
     *
     * @param name the value for uuid_user.name
     *
     * @mbg.generated Thu Apr 25 18:56:40 CST 2019
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column uuid_user.created_datetime
     *
     * @return the value of uuid_user.created_datetime
     *
     * @mbg.generated Thu Apr 25 18:56:40 CST 2019
     */
    public LocalDateTime getCreatedDatetime() {
        return createdDatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column uuid_user.created_datetime
     *
     * @param createdDatetime the value for uuid_user.created_datetime
     *
     * @mbg.generated Thu Apr 25 18:56:40 CST 2019
     */
    public void setCreatedDatetime(LocalDateTime createdDatetime) {
        this.createdDatetime = createdDatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column uuid_user.updated_datetime
     *
     * @return the value of uuid_user.updated_datetime
     *
     * @mbg.generated Thu Apr 25 18:56:40 CST 2019
     */
    public LocalDateTime getUpdatedDatetime() {
        return updatedDatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column uuid_user.updated_datetime
     *
     * @param updatedDatetime the value for uuid_user.updated_datetime
     *
     * @mbg.generated Thu Apr 25 18:56:40 CST 2019
     */
    public void setUpdatedDatetime(LocalDateTime updatedDatetime) {
        this.updatedDatetime = updatedDatetime;
    }
}