package com.at.springboot.mybatis.mapper;

import com.at.springboot.mybatis.po.UuidUser;
import com.at.springboot.mybatis.po.UuidUserExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface UuidUserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table uuid_user
     *
     * @mbg.generated Thu Apr 25 18:56:40 CST 2019
     */
    long countByExample(UuidUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table uuid_user
     *
     * @mbg.generated Thu Apr 25 18:56:40 CST 2019
     */
    int deleteByExample(UuidUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table uuid_user
     *
     * @mbg.generated Thu Apr 25 18:56:40 CST 2019
     */
    int deleteByPrimaryKey(byte[] bid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table uuid_user
     *
     * @mbg.generated Thu Apr 25 18:56:40 CST 2019
     */
    int insert(UuidUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table uuid_user
     *
     * @mbg.generated Thu Apr 25 18:56:40 CST 2019
     */
    int insertSelective(UuidUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table uuid_user
     *
     * @mbg.generated Thu Apr 25 18:56:40 CST 2019
     */
    List<UuidUser> selectByExample(UuidUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table uuid_user
     *
     * @mbg.generated Thu Apr 25 18:56:40 CST 2019
     */
    UuidUser selectByPrimaryKey(byte[] bid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table uuid_user
     *
     * @mbg.generated Thu Apr 25 18:56:40 CST 2019
     */
    int updateByExampleSelective(@Param("record") UuidUser record, @Param("example") UuidUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table uuid_user
     *
     * @mbg.generated Thu Apr 25 18:56:40 CST 2019
     */
    int updateByExample(@Param("record") UuidUser record, @Param("example") UuidUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table uuid_user
     *
     * @mbg.generated Thu Apr 25 18:56:40 CST 2019
     */
    int updateByPrimaryKeySelective(UuidUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table uuid_user
     *
     * @mbg.generated Thu Apr 25 18:56:40 CST 2019
     */
    int updateByPrimaryKey(UuidUser record);
}