package org.at.cmware.persistent.entity;

// Generated 2011-10-1 14:26:05 by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Sequense generated by hbm2java
 */
@Entity
@Table(name = "sequense", catalog = "cmware")
//@NamedNativeQueries({
//    @NamedNativeQuery(
//        name="CALL.NEXTVAL.BY_SEQNAME",
//        query="{call nextval(:seq_name)}",
//        hints={
//                @QueryHint(
//                        name="org.hibernate.callable",
//                        value="true"
//                )
//        },
//        resultClass=Sequense.class
//    ),
//    @NamedNativeQuery(
//        name="QUERY.CURRVAL.BY_SEQNAME",
//        query="select currval(:seq_name)"
//    )
//})
public class Sequense implements java.io.Serializable {

	private String seqName;
	private int seqIncrement = 1;
	private int seqMinValue = 1;
	private long seqMaxValue = Long.MAX_VALUE;
	private long seqCurrValue = 1;
	private boolean seqCycle = true;

	public Sequense() {
	}

	public Sequense(String seqName, int seqIncrement, int seqMinValue, long seqMaxValue, long seqCurrValue,
			boolean seqCycle) {
		this.seqName = seqName;
		this.seqIncrement = seqIncrement;
		this.seqMinValue = seqMinValue;
		this.seqMaxValue = seqMaxValue;
		this.seqCurrValue = seqCurrValue;
		this.seqCycle = seqCycle;
	}

	@Id
	@Column(name = "seq_name", unique = true, nullable = false, length = 256)
	public String getSeqName() {
		return this.seqName;
	}

	public void setSeqName(String seqName) {
		this.seqName = seqName;
	}

	@Column(name = "seq_increment", nullable = false)
	public int getSeqIncrement() {
		return this.seqIncrement;
	}

	public void setSeqIncrement(int seqIncrement) {
		this.seqIncrement = seqIncrement;
	}

	@Column(name = "seq_min_value", nullable = false)
	public int getSeqMinValue() {
		return this.seqMinValue;
	}

	public void setSeqMinValue(int seqMinValue) {
		this.seqMinValue = seqMinValue;
	}

	@Column(name = "seq_max_value", nullable = false)
	public long getSeqMaxValue() {
		return this.seqMaxValue;
	}

	public void setSeqMaxValue(long seqMaxValue) {
		this.seqMaxValue = seqMaxValue;
	}

	@Column(name = "seq_curr_value", nullable = false)
	public long getSeqCurrValue() {
		return this.seqCurrValue;
	}

	public void setSeqCurrValue(long seqCurrValue) {
		this.seqCurrValue = seqCurrValue;
	}

	@Column(name = "seq_cycle", nullable = false)
	public boolean isSeqCycle() {
		return this.seqCycle;
	}

	public void setSeqCycle(boolean seqCycle) {
		this.seqCycle = seqCycle;
	}

}
